import { COLLECTIONS } from './enums.js';

export const fieldsSettings = {
  [COLLECTIONS.PRODUCTS]: [
    'id',
    'name',
    'description',
    'price',
    'expedite_price',
    'ecc_buffered_price',
    'min_quantity',
    'max_quantity',
    'min_ram_size',
    'max_ram_size',
    'min_hard_drive_size',
    'max_hard_drive_size',
    'min_rdb_quantity',
    'max_rdb_quantity',
    'sort',
    'memory_price',
    'average_customer_rating',
    'reviews',
    'attributes.*',
    'attributes.attribute.*',
    'attributes.attribute.product_attributes*',
    'drive_options.*',
    'hard_drive_options.*',
    'rdb_options.*',
    'processor_options.*',
    'raid_controller_options.*',
  ],
  [COLLECTIONS.REVIEWS]: [
    'id',
    'author_name',
    'message',
    'product.*',
    'rating',
  ],
  [COLLECTIONS.COUNTRIES]: ['code', 'name'],
  [COLLECTIONS.ADDRESS]: ['*'],
  [COLLECTIONS.SHIPPING_ADDRESS]: [
    'email',
    'first_name',
    'last_name',
    'company',
    'telephone',
    'fax',
    'address.*',
  ],
  [COLLECTIONS.SHIPPING_METHODS]: ['*'],
  [COLLECTIONS.ORDER]: [
    'id',
    'date_created',
    'date_updated',
    'cart.*',
    'cart.cart_items.*',
    'address.*',
    'shipping_method.*',
  ],
  [COLLECTIONS.ARTICLE]: [
    'id',
    'name',
    'short_description',
    'date_published',
    'cover_image',
    'full_story',
    'tags',
  ],
  [COLLECTIONS.FAQ]: ['*'],
  [COLLECTIONS.NEWSLETTER]: ['*'],
  [COLLECTIONS.DIRECTUS_USERS]: ['id', 'email'],
  [COLLECTIONS.COMPANY_MESSAGES]: ['*'],
};
